services:
    av_platform.antispam:
        class: AV\PlatformBundle\Antispam\AVAntispam
        arguments: [@mailer, %locale%, 50]
        tags:
            - { name: twig.extension }
    av_platform.doctrine.notification:
        class: AV\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    av_platform.validator.antiflood:                              # Le nom du service
        class: AV\PlatformBundle\Validator\AntifloodValidator     # la classe du service (ici, notre validateur)
        arguments: [@request_stack, @doctrine.orm.entity_manager] # Les données qu'on injecte : la requête et l'EntityManager
        tags:
            - { name: validator.constraint_validator, alias: av_platform_antiflood } # C'est avec l'alias qu'on retrouvera le service
    av_platform.beta.html:
        class: AV\PlatformBundle\Beta\BetaHtml
    av_platform.beta.listener:
        class: AV\PlatformBundle\Beta\BetaListener
        arguments: [@av_platform.beta.html, "2015-10-27"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }
#    av_platform.example:
#        class: AV\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
